### ISSUE TITLE
Optical flow

### ISSUE THREAD

**Issue by Ruinmou** [erikalu/omnimatte#13]
When I was preparing my data set, I had a question in step 4. What is the difference between forward optical flow and reverse optical flow? After I generate my own optical flow, step 5 prompts   ' magic number incorrect. Invalid. Flo file '

**Comment by erikalu** [comment]
We need to compute both the flow from t -> t+1 and the flow from t+1 -> t. So if using an optical flow model like RAFT, to create the backwards flow, just flip the order of the image pairs.

The magic number has to do with the Middlebury .flo format: https://github.com/princeton-vl/RAFT/blob/master/core/utils/frame_utils.py#L12
If you use RAFT, you won't have to worry about it because the flo files will be saved in the correct format.

**Comment by Ruinmou** [comment]
Okay, thank you, I have completed my task through the above tips, but I now have a new problem.
`/home/haimou/anaconda3/envs/omn/lib/python3.8/site-packages/torch/nn/functional.py:3451: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn(
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    main()
  File "train.py", line 42, in main
    train(model, dataset, visualizer, opt)
  File "train.py", line 54, in train
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "/home/haimou/桌面/project_all/omnimatte/third_party/data/__init__.py", line 92, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/haimou/anaconda3/envs/omn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/haimou/anaconda3/envs/omn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/haimou/anaconda3/envs/omn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/haimou/anaconda3/envs/omn/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/haimou/anaconda3/envs/omn/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/haimou/anaconda3/envs/omn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/haimou/anaconda3/envs/omn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/haimou/桌面/project_all/omnimatte/data/omnimatte_dataset.py", line 130, in __getitem__
    data_t1 = self.get_transformed_item(index, transform_params)
  File "/home/haimou/桌面/project_all/omnimatte/data/omnimatte_dataset.py", line 177, in get_transformed_item
    bg_warp = self.get_background_uv(index, mask_w, mask_h) * 2 - 1
  File "/home/haimou/桌面/project_all/omnimatte/data/omnimatte_dataset.py", line 318, in get_background_uv
    H = self.homographies[index]
IndexError: list index out of range
`
my homographies.txt
`size: 854 480
bounds: 0 853 0 479`

I don’t know how to get the homography
